### PR TITLE
edit pass: manage-access-at-scale

### PR DESCRIPTION
**Pull request by ShawnJackson**
@andredm7  – Please review the copy edit to your article, address the following comments, and let me know if I’ve changed the technical meaning anywhere. This is for TFS work request 69662.

Comments:
- Under the first H2 heading, I flattened the heading hierarchy a bit to avoid going down to the H4 level. Please confirm that this is OK.
- This text makes a promise about the future: "Azure AD currently integrates with Workday. It will integrate with more apps in the future." Please ensure that your legal contact has approved this statement.
- In the text "you can log in to several SaaS applications by using a single user account and password," please confirm that "log in" is more accurate than "sign in" (which is the Microsoft style preference).

### CODE REVIEW

**Comment by andredm7** [comment]
Hi Shawn,

Thanks for your review! The only change that I didn’t approve was the one about the “on-premises HR systems”:

[cid:image002.jpg@01D22BC8.DA656F60]

The others that require LCA, please go ahead and make edits here, I will not be able to reach out to LCA any time soon. I’m leaving for vacation today.

That said, please go ahead and remove the statement about future apps. I’m also open to accept suggestions for these words: "simple," "secure," and "protect.".

Please update the PR, and I’ll review it all.

--Andre Della Monica

**Comment by andredm7** [comment]
@Shawn Jackson (Aquent LLC)<mailto:v-shawja@microsoft.com> – CIL

--Andre Della Monica

**Comment by ShawnJackson** [comment]
@andredm7 - Thanks for the feedback, Andre. I'll make those changes tomorrow.

**Comment by ShawnJackson** [comment]
@andredm7 - I removed that one "in the future" sentence and made a few other changes to tone down "simple," "secure," and "protect." Please do proceed with that legal review if possible, to make sure that all the claims in this article are OK to make. And let me know if you want me to change anything else. Thanks!

**Comment by ShawnJackson** [comment]
@andredm7 - I fixed merge conflicts. Please confirm that the content looks OK.

**Comment by andredm7** [comment]
@Shawn Jackson (Aquent LLC)<mailto:v-shawja@microsoft.com>, I just checked, everything looks good! Thanks!

--Andre Della Monica

**Pull request merged**
