### PR TITLE
CC77368: Corrected links to images

### PR DESCRIPTION
**Pull request by v-makoud**
Hello, @yuridio,
This proposed file change comes from https://github.com/MicrosoftDocs/EMDocs.it-it/pull/17 .
Could you review this contribution and help to merge if agreed?
Many thanks in advance.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@v-makoud : Thanks for your contribution! The author, @yuridio, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
@v-makoud - You should pull this change over to the private repo so you can stage the change first. [You can use these steps](https://review.docs.microsoft.com/en-us/help/contribute/resolve-merge-conflicts?branch=master#method-2---fetch-the-upstream-references) to pull the commits over to your local copy of the private repo.

**Comment by v-maudel** [comment]
Created a new PR here: https://github.com/MicrosoftDocs/EMDocs-pr/pull/786

@v-makoud: please-close

**Comment by ktoliver** [comment]
#please-close

**Pull request closed without merging**
