### PR TITLE
Fix PowerShell command

### PR DESCRIPTION
**Pull request by milesgratz**
The "Issuer" nested property on that object does not make it obvious this is a Microsoft certificate since it is chained to a common DigiCert Issuing CA. Omitting the "Issuer" nested property returns both the "Issuer" and the "Subject" which more helpful.

```
PS C:\> $request.ServicePoint.Certificate.Issuer
CN=DigiCert SHA2 Secure Server CA, O=DigiCert Inc, C=US
```

```
PS C:\> $request.ServicePoint.Certificate

       Handle Issuer                                                  Subject
       ------ ------                                                  -------
2338365787840 CN=DigiCert SHA2 Secure Server CA, O=DigiCert Inc, C=US CN=ssl.aadrm.us, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
```

### CODE REVIEW

**Comment by PRMerger9** [comment]
@milesgratz : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @milesgratz Could you take a moment to sign the CLA?

Thanks.

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@mlottner Could you review the proposed update to your article? Thanks.

**Comment by ktoliver** [comment]
@mlottner Could you review this open pull request from October?

Thanks.

**Comment by dcurwin** [comment]
@batamig - Can you review this PR?

**Comment by dcurwin** [comment]
#reassign:batamig

**Comment by batamig** [comment]
Hi @dcurwin thanks for the re-assign and @milesgratz, thank you for this feedback.

I'm just going to check with the team to verify the fix, and then we'll get this page updated as needed.

Thanks for your contribution to docs!

**Comment by batamig** [comment]
PM team approved
#sign-off

**Pull request merged**
