### PR TITLE
Update EMS FAQs

### PR DESCRIPTION
**Pull request by EMSPlanner**
Adding CAS and AATP (2 new products). Point customers to the Azure portal as an intended experience for Intune, AADP, AIP and CAS.

### CODE REVIEW

**Comment by EMSPlanner** [comment]
This is submitted by the EMS Planner - Tatiana Lewis - tatianal@microsoft.com

Please contact if there are any questions

**Comment by PRMerger7** [comment]
@EMSPlanner : Thanks for your contribution to the Azure documentation! The author, @nathbarn, has been notified to review your proposed change.

**Comment by dougeby** [comment]
#sign-off.
The author is no longer with Microsoft. The content is approved.

**Comment by PRMerger12** [comment]
@dougeby: I'm sorry - only the author of this article, @nathbarn, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
