### PR TITLE
Edit to GCC High exclusions for Remote Help app

### PR DESCRIPTION
**Pull request by Brenduns**
Remote help app content publishes on 11/24/2021 by 11:00am pacific,  via work item https://msazure.visualstudio.com/Intune/_workitems/edit/9843480 and PR https://msazure.visualstudio.com/Intune/_workitems/edit/9843480.   The product group has asked for this exclusion of support for GCC high be added to this article.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@Brenduns : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@dcurwin Thanks for the review; merging.

**Pull request merged**
